=== kumm/claraxsd-maven-plugin/src/main/resources/trial/clara-com_vaadin_ui.xsd
<?xml version="1.0"?>
<!--
Copyright 2014 kumm.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<xs:schema version="1.1"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:import:com.vaadin.ui"
           xmlns:b="urn:clara:base"
           xmlns:r="urn:clara:root"
           elementFormDefault="qualified">
    
    <xs:import schemaLocation="clara.xsd" namespace="urn:clara:root"/>
    <xs:import schemaLocation="clara_base.xsd" namespace="urn:clara:base"/>

    <xs:element name="VerticalLayout">
        <xs:complexType>
            <!-- This would be much better, but breaks attribute level autocomplete in NetBeans -->
            <!-- <xs:sequence>
                <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            -->
            <!-- so we need a group of all components to make NetBeans happy -->
            <xs:group ref="r:AllComponentsGroup" minOccurs="0" maxOccurs="unbounded"/>
            <xs:attributeGroup ref="b:AbstractComponentAttributeGroup"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="HorizontalLayout">
        <xs:complexType>
            <xs:group ref="r:AllComponentsGroup" minOccurs="0" maxOccurs="unbounded"/>
            <xs:attributeGroup ref="b:AbstractComponentAttributeGroup"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="CssLayout">
        <xs:complexType>
            <xs:group ref="r:AllComponentsGroup" minOccurs="0" maxOccurs="unbounded"/>
            <xs:attributeGroup ref="b:AbstractComponentAttributeGroup"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Button">
        <xs:complexType>
            <xs:attributeGroup ref="b:AbstractComponentAttributeGroup"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Label">
        <xs:complexType>
            <xs:attributeGroup ref="b:AbstractComponentAttributeGroup"/>
            <xs:attribute name="value"/>
            <xs:attribute name="contentMode"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Table">
        <xs:complexType>
            <xs:attributeGroup ref="b:AbstractComponentAttributeGroup"/>
            <xs:attribute name="pageLength"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="DateField">
        <xs:complexType>
            <xs:attributeGroup ref="b:AbstractFieldAttributeGroup"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Select">
        <xs:complexType>
            <xs:attributeGroup ref="b:AbstractFieldAttributeGroup"/>
            <xs:attribute name="itemCaptionPropertyId"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== kumm/claraxsd-maven-plugin/src/main/resources/trial/demo-layout.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 
    Modify this XML layout definition and click the Update button
    to see your changes on the right.

    Try to move around the id attributes to see effects of the
    binding. For example you can move the bound data source of
    the Table to the Select. Or you can change the value change
    event handler from the RatingStars component to the DateField
    by moving the value-field id.
    
    Have fun!
     
-->
<VerticalLayout 
    xmlns="urn:import:com.vaadin.ui"
    xmlns:l="urn:vaadin:parent"
    xmlns:a="urn:import:org.vaadin.teemu.ratingstars"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
urn:import:com.vaadin.ui clara-com_vaadin_ui.xsd
urn:import:org.vaadin.teemu.ratingstars clara-org_vaadin_teemu_ratingstars.xsd"
    margin="true"
    spacing="true">

    <Label id="label" contentMode="HTML" value="Welcome to &lt;strong&gt;Clara&lt;/strong&gt; demo application." />

    <HorizontalLayout caption="Horizontal button row" spacing="true">
        <Button id="button" caption="Click to invoke the controller" />
        <Button id="another-button" width="200px" caption="Click me too" />
    </HorizontalLayout>
    
    <DateField caption="Select a date" id="date" immediate="true" />

    <CssLayout width="60%">
        <Table id="person-list" width="100%" 
            caption="Controller provides my datasource..." pageLength="2" />
        <Select caption="...try moving the person-list id here" 
            itemCaptionPropertyId="Name" />
    </CssLayout>

    <a:RatingStars id="value-field" l:componentAlignment="MIDDLE_CENTER" 
        immediate="true" caption="Add-ons work too" />
    
</VerticalLayout>
